### ISSUE TITLE
Create Transform component

### ISSUE THREAD

**Issue by Winterherr** [Leonetienne/TornadoPlatoApp#7]
Component for controlling the position in space. Similar to the Rotator component. As of now the camera has its own component to modify its position.

**Comment by Leonetienne** [comment]
huh? es gibt doch https://github.com/Leonetienne/TornadoPlatoApp/blob/master/Plato/Transform.h, was by-default auf jedem gameobjekt ist

**Comment by Winterherr** [comment]
aso
